CREATE TABLE LAST_STEP_OF_REGISTERING_EMPLOYEE(
    id SERIAL PRIMARY KEY NOT NULL,
    password VARCHAR(64),
    email VARCHAR(64) UNIQUE,
    user_id INTEGER NOT NULL,
    link_registering TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES EMPLOYEE(id)
);